name: yeast
organism: yeast
sequence_length: 150
data_root: data/yeast
input_channels: 6
task_mode: yeast
random_region_length: 80
test_set:
  random:
    subset_ids_file: data/yeast/test_subset_ids/all_random_seqs.csv
  snv:
    subset_ids_file: data/yeast/test_subset_ids/all_SNVs_seqs.csv
  genomic:
    subset_ids_file: data/yeast/test_subset_ids/yeast_seqs.csv
flanking_sequence:
  five_prime: "GCTAGCAGGAATGATGCAAAAGGTTCCCGATTCGAACTGCATTTTTTTCACATCTCG"
  three_prime: "GGTTACGGCTGTT"
